# Generated by Django 4.1.6 on 2023-02-10 09:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'meal')},
        ),
        migrations.AlterIndexTogether(
            name='rate',
            index_together={('user', 'meal')},
        ),
    ]
